default_language_version:
  python: python3.9
repos:
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
    - id: autopep8

-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    - id: autoflake
      args: [--in-place, --remove-all-unused-imports, --ignore-init-module-imports]

-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    - id: black
    
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    - id: flake8