name: Python package using Poetry

on: [push]

jobs:
  build:

    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |          
          pip install --upgrade pip
          pip install poetry

      - name: Install anchorpy
        run: |
          poetry install

      - name: Run black
        run: |
          poetry run black .

      - name: Run pytest
        run: |
          poetry run pytest -v --color=yes -o log_cli=false