name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dev package with dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]

      - name: Run black
        run: |
          black .

      - name: Run pytest
        run: |
          pytest -v --color=yes